# Generated by Django 4.2.2 on 2023-06-22 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=256)),
                ('book_review', models.CharField(max_length=2048)),
                ('book_rating', models.FloatField(default=0.0)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id', to='user_api.usermodel')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
