# Generated by Django 4.2.2 on 2023-06-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0002_alter_book_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='user',
        ),
    ]
