# Generated by Django 4.2.2 on 2023-06-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0003_rename_user_id_book_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_review',
            new_name='user_review',
        ),
    ]
